/*
 * Sys.java
 *
 * Created on __DATE__, __TIME__
 */

package ui.main;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JFrame;

import ui.listener.MainWinListener;
import ui.merchandises.Helps;
import ui.merchandises.MerRetailQuery;
import ui.merchandises.MerchandiseIn;
import ui.merchandises.MerchandiseManager;
import ui.merchandises.MerchandiseRetail;
import ui.merchandises.MerchandiseTotal;
import ui.merchandises.MerchandisesQuery;
import ui.merchandises.UserManager;
import constants.MisConstants;

/**
 * 
 * @author __USER__
 */
public class Sys extends javax.swing.JFrame {

	public String userType;
	public String userName;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public Sys(String userType, String userName) {
		this.userType = userType;
		this.userName = userName;
		initComponents();
		if (userType.equals("1")) {
			this.contentsMenuItem.setEnabled(false);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		saveMerchandise = new javax.swing.JMenuItem();
		exitMenuItem = new javax.swing.JMenuItem();
		editMenu = new javax.swing.JMenu();
		cutMenuItem = new javax.swing.JMenuItem();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		helpMenu = new javax.swing.JMenu();
		contentsMenuItem = new javax.swing.JMenuItem();
		aboutMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u51fa\u5165\u5e93Mis\u7ba1\u7406");
		setName("sys");

		fileMenu.setText("\u51fa\u5165\u5e93\u7ba1\u7406");

		saveMerchandise.setText("\u51fa\u5165\u5e93\u767b\u8bb0");
		saveMerchandise.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				saveMerchandiseActionPerformed(evt);
			}
		});
		fileMenu.add(saveMerchandise);

		exitMenuItem.setText("\u7cfb\u7edf\u9000\u51fa");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		editMenu.setText("\u5546\u54c1\u7ba1\u7406");

		cutMenuItem.setText("\u5546\u54c1\u65b0\u589e\u5f55\u5165");
		cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cutMenuItemActionPerformed(evt);
			}
		});
		editMenu.add(cutMenuItem);

		jMenuItem3.setText("\u5546\u54c1\u96f6\u552e");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		editMenu.add(jMenuItem3);

		menuBar.add(editMenu);

		jMenu1.setText("\u4ea4\u6613\u67e5\u8be2");

		jMenuItem1.setText("\u51fa\u5165\u5e93\u8bb0\u5f55\u67e5\u8be2");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuItem2.setText("\u5546\u54c1\u5e93\u5b58\u67e5\u8be2");
		jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem2ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem2);

		jMenuItem4.setText("\u5546\u54c1\u96f6\u552e\u67e5\u8be2");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem4);

		menuBar.add(jMenu1);

		helpMenu.setText("\u7528\u6237\u7ba1\u7406");

		contentsMenuItem.setText("\u7cfb\u7edf\u7528\u6237\u7ba1\u7406");
		contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				contentsMenuItemActionPerformed(evt);
			}
		});
		helpMenu.add(contentsMenuItem);

		aboutMenuItem.setText("\u5173\u4e8e\u7cfb\u7edf");
		aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutMenuItemActionPerformed(evt);
			}
		});
		helpMenu.add(aboutMenuItem);

		menuBar.add(helpMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 778,
							Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 416,
							Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {
		MerRetailQuery mr = new MerRetailQuery();
		setWindowSize(mr, "商品零售查询");
	}

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		MerchandiseRetail mr = new MerchandiseRetail(userName);
		setWindowSize(mr, "商品零售管理");
	}

	private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		Helps mer = new Helps();
		setWindowSize(mer, "关于");
	}

	private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		UserManager mer = new UserManager();
		setWindowSize(mer, "用户管理");
	}

	private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		MerchandiseManager mer = new MerchandiseManager();

		setWindowSize(mer, "商品录入管理");
	}

	private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
		MerchandiseTotal mer = new MerchandiseTotal();
		setWindowSize(mer, "货物存入记录统计");
	}

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		MerchandisesQuery mer = new MerchandisesQuery();
		setWindowSize(mer, "货物存入记录查询");
	}

	private void saveMerchandiseActionPerformed(java.awt.event.ActionEvent evt) {
		MerchandiseIn mi = new MerchandiseIn(userName);
		setWindowSize(mi, "货物存入管理");

	}

	public void setWindowSize(JFrame jframe, String title) {
		this.setAlwaysOnTop(false);
		this.setEnabled(false);
		jframe.setVisible(true);
		jframe.setLocation(300, 150);
		jframe.addWindowListener(new MainWinListener(this));
		jframe.setTitle(title);

		Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
		int sysw = MisConstants.winW;
		int sysh = MisConstants.winH;
		jframe.setBounds((d.width - sysw) / 2, (d.height - sysh) / 2, sysw, sysh);
	}

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
		this.dispose();
	}// GEN-LAST:event_exitMenuItemActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Sys("1", "1").setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem contentsMenuItem;
	private javax.swing.JMenuItem cutMenuItem;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem saveMerchandise;
	// End of variables declaration//GEN-END:variables

}