/*
 * EditMerchandise.java
 *
 * Created on __DATE__, __TIME__
 */

package ui.merchandises;

import java.util.List;

import javax.swing.JOptionPane;

import bean.Merchandise;
import db.DbLogicServie;

/**
 * 
 * @author __USER__
 */
public class EditMerchandise extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2976586109019988629L;
	String merchandisInfoId;

	/** Creates new form EditMerchandise */
	public EditMerchandise(String merchandisInfoId) {
		this.merchandisInfoId = merchandisInfoId;
		initComponents();
		initFrameValue(merchandisInfoId);
	}

	@SuppressWarnings("unchecked")
	void initFrameValue(String merchandisId) {
		String[] arg = { merchandisId };
		List list = DbLogicServie.getMerchandiseInfo(arg);
		if (list.size() > 0) {
			Merchandise mer = (Merchandise) list.get(0);
			this.tf_MerBrand.setText(mer.getMerchandiseBrand());
			this.tf_MerName.setText(mer.getMerchandiseName());
			this.tf_MerTand.setText(mer.getMerchandiseTandard());
			this.tf_MerType.setText(mer.getMerchandiseType());
			this.tf_MerPrice.setText(mer.getMerchandisePrice());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		tf_MerBrand = new javax.swing.JTextField();
		tf_MerType = new javax.swing.JTextField();
		tf_MerName = new javax.swing.JTextField();
		tf_MerTand = new javax.swing.JTextField();
		bt_save = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		tf_MerPrice = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("\u5546\u54c1\u540d\u79f0\uff1a");

		jLabel2.setText("\u5546\u54c1\u89c4\u683c\uff1a");

		jLabel3.setText("\u5546\u54c1\u54c1\u724c\uff1a");

		jLabel4.setText("\u5546\u54c1\u7c7b\u578b\uff1a");

		bt_save.setText("\u4fdd\u5b58");
		bt_save.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bt_saveActionPerformed(evt);
			}
		});

		jLabel5.setText("\u5546\u54c1\u5355\u4ef7:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout
							.setHorizontalGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
																	layout
																						.createSequentialGroup()
																						.addGap(35, 35, 35)
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.TRAILING)
																																.addComponent(
																																					jLabel2)
																																.addComponent(
																																					jLabel1))
																						.addPreferredGap(
																											javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(
																																					tf_MerTand,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																					tf_MerName,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					147,
																																					javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addPreferredGap(
																											javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.LEADING)
																																.addGroup(
																																					layout
																																										.createSequentialGroup()
																																										.addComponent(
																																															jLabel3)
																																										.addPreferredGap(
																																															javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																															tf_MerBrand,
																																															javax.swing.GroupLayout.PREFERRED_SIZE,
																																															javax.swing.GroupLayout.DEFAULT_SIZE,
																																															javax.swing.GroupLayout.PREFERRED_SIZE))
																																.addGroup(
																																					layout
																																										.createSequentialGroup()
																																										.addComponent(
																																															jLabel4)
																																										.addPreferredGap(
																																															javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																										.addComponent(
																																															tf_MerType,
																																															javax.swing.GroupLayout.PREFERRED_SIZE,
																																															javax.swing.GroupLayout.DEFAULT_SIZE,
																																															javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGap(40, 40, 40)
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.LEADING)
																																.addGroup(
																																					layout
																																										.createSequentialGroup()
																																										.addComponent(
																																															jLabel5)
																																										.addPreferredGap(
																																															javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																										.addComponent(
																																															tf_MerPrice,
																																															javax.swing.GroupLayout.PREFERRED_SIZE,
																																															javax.swing.GroupLayout.DEFAULT_SIZE,
																																															javax.swing.GroupLayout.PREFERRED_SIZE))
																																.addComponent(
																																					bt_save))
																						.addContainerGap(
																											25,
																											Short.MAX_VALUE)));

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { tf_MerBrand, tf_MerName,
							tf_MerPrice, tf_MerTand, tf_MerType });

		layout
							.setVerticalGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
																	layout
																						.createSequentialGroup()
																						.addGap(36, 36, 36)
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(
																																					jLabel1)
																																.addComponent(
																																					jLabel3)
																																.addComponent(
																																					tf_MerName,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																					tf_MerBrand,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																					jLabel5)
																																.addComponent(
																																					tf_MerPrice,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGap(30, 30, 30)
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(
																																					jLabel2)
																																.addComponent(
																																					jLabel4)
																																.addComponent(
																																					tf_MerTand,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																					tf_MerType,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																					bt_save))
																						.addContainerGap(
																											62,
																											Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {
		String merBrand = this.tf_MerBrand.getText();
		String merName = this.tf_MerName.getText();
		String merTand = this.tf_MerTand.getText();
		String merType = this.tf_MerType.getText();
		String merPrice = this.tf_MerPrice.getText();
		Merchandise mer = new Merchandise();
		mer.setMerchandiseBrand(merBrand);
		mer.setMerchandiseName(merName);
		mer.setMerchandiseType(merType);
		mer.setMerchandiseTandard(merTand);
		mer.setMerchandisePrice(merPrice);
		mer.setMerchandiseId(merchandisInfoId);
		if (DbLogicServie.updateMerchandiseInfo(mer)) {
			JOptionPane.showMessageDialog(null, "更新成功", "提示信息", JOptionPane.INFORMATION_MESSAGE);
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EditMerchandise("").setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton bt_save;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField tf_MerBrand;
	private javax.swing.JTextField tf_MerName;
	private javax.swing.JTextField tf_MerPrice;
	private javax.swing.JTextField tf_MerTand;
	private javax.swing.JTextField tf_MerType;
	// End of variables declaration//GEN-END:variables

}