/*
 * Helps.java
 *
 * Created on __DATE__, __TIME__
 */

package ui.merchandises;

/**
 *
 * @author  __USER__
 */
public class Helps extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8139346575291478505L;
	/** Creates new form Helps */
	public Helps() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 24));
		jLabel1.setText("\u5546\u54c1\u51fa\u5165\u5e93\u7ba1\u7406\u7cfb\u7edf");

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 1, 12));
		jLabel2.setText("Version : V1.0");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
							javax.swing.GroupLayout.Alignment.TRAILING,
							layout.createSequentialGroup().addContainerGap(133, Short.MAX_VALUE).addGroup(
												layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																	.addComponent(jLabel2).addComponent(jLabel1))
												.addGap(51, 51, 51)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
							layout.createSequentialGroup().addGap(29, 29, 29).addComponent(jLabel1).addGap(34, 34, 34)
												.addComponent(jLabel2).addContainerGap(187, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Helps().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	// End of variables declaration//GEN-END:variables

}