/*
 * MerchandiseTotal.java
 *
 * Created on __DATE__, __TIME__
 */

package ui.merchandises;

import java.util.List;

import ui.model.MerchandiseTableModel;
import util.DateUtil;
import bean.ItemData;
import db.DbLogicServie;

/**
 * 
 * @author __USER__
 */
public class MerchandiseTotal extends MerchandisesQuery {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3078363070732674516L;

	/** Creates new form MerchandiseTotal */
	public MerchandiseTotal() {
		initComponents(); 
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
							Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
							Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	@SuppressWarnings("unchecked")
	@Override
	public void b_queryMouseClicked(java.awt.event.MouseEvent evt) {
		String[] arg = { ((ItemData) super.jcb_MerType.getSelectedItem()).code,
							((ItemData) super.jcb_MerDealType.getSelectedItem()).code,
							DateUtil.string2Format(super.tf_startTime.getText(), DateUtil.YMD, DateUtil.YMD),
							DateUtil.string2Format(super.tf_endTime.getText(), DateUtil.YMD, DateUtil.YMD) };
		List list = DbLogicServie.getMerchandiseTotal(arg);
		super.queryList = list;
		super.fileName = super.tf_startTime.getText() + "-" + super.tf_endTime.getText() + "商品库存信息.xls";
		MerchandiseTableModel m_table = new MerchandiseTableModel(queryList);
		MerchandiseTableModel.colnumNames = new String[] { "商品名称 ", "商品规格", "商品品牌", "商品总额", "商品库存" };
		MerchandiseTableModel.fieldNames = new String[] { "merchandiseName", "merchandiseTandard", "merchandiseBrand",
							"m_total", "m_count" };
		m_table.setData(list);
		super.t_MerRecords.setModel(m_table);

	}

	// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MerchandiseTotal().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}