/*
 * MerchandiseRetail.java
 *
 * Created on __DATE__, __TIME__
 */

package ui.merchandises;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

import ui.model.MerchandiseRetailTabelModel;
import util.DateUtil;
import bean.ItemData;
import bean.MerRetail;
import bean.Merchandise;
import db.DbLogicServie;

/**
 * 
 * @author __
 */
public class MerchandiseRetail extends javax.swing.JFrame {
	private String userName;
	public static String merchandiseRetailId = null;
	public List<MerRetail> merDetailList = new ArrayList<MerRetail>();
	public List<String> merchandiseRetailIds = new ArrayList<String>();
	/**
	 * 
	 */
	private static final long serialVersionUID = 1701517251547443033L;

	/** Creates new form MerchandiseRetail */
	@SuppressWarnings("unchecked")
	public MerchandiseRetail(String userName) {
		this.userName = userName;
		initComponents();

		// init mertype for select
		List list = DbLogicServie.getMerchandiseInfo(null);
		if ((list != null) && (list.size() > 0)) {
			String[] items = new String[list.size()];
			for (int i = 0; i < list.size(); ++i) {
				Merchandise mer = (Merchandise) list.get(i);
				items[i] = mer.getMerchandiseName();
				ItemData data = new ItemData(mer.getMerchandiseId(), mer.getMerchandiseName());
				this.jcb_MerType.addItem(data);
			}

		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tb_Merchandise = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		jcb_MerType = new javax.swing.JComboBox();
		jLabel2 = new javax.swing.JLabel();
		jsp_MerCount = new javax.swing.JSpinner();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		bt_add = new javax.swing.JButton();
		bt_save = new javax.swing.JButton();
		bt_del = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jScrollPane1.setViewportView(tb_Merchandise);

		jLabel1.setText("\u5546\u54c1\u7c7b\u578b\uff1a");

		jLabel2.setText("\u5546\u54c1\u6570\u91cf\uff1a");

		jLabel3.setText("\u5907     \u6ce8\uff1a");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane2.setViewportView(jTextArea1);

		bt_add.setText("\u589e\u52a0");
		bt_add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bt_addActionPerformed(evt);
			}
		});

		bt_save.setText("\u4fdd\u5b58");
		bt_save.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bt_saveActionPerformed(evt);
			}
		});

		bt_del.setText("\u5254\u9664");
		bt_del.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bt_delActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout
							.setHorizontalGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
																	layout
																						.createSequentialGroup()
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.LEADING)
																																.addGroup(
																																					layout
																																										.createSequentialGroup()
																																										.addGap(
																																															49,
																																															49,
																																															49)
																																										.addGroup(
																																															layout
																																																				.createParallelGroup(
																																																									javax.swing.GroupLayout.Alignment.LEADING)
																																																				.addGroup(
																																																									layout
																																																														.createSequentialGroup()
																																																														.addComponent(
																																																																			jLabel1)
																																																														.addPreferredGap(
																																																																			javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																																														.addComponent(
																																																																			jcb_MerType,
																																																																			javax.swing.GroupLayout.PREFERRED_SIZE,
																																																																			124,
																																																																			javax.swing.GroupLayout.PREFERRED_SIZE)
																																																														.addGap(
																																																																			60,
																																																																			60,
																																																																			60)
																																																														.addComponent(
																																																																			jLabel2)
																																																														.addPreferredGap(
																																																																			javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																																														.addComponent(
																																																																			jsp_MerCount,
																																																																			javax.swing.GroupLayout.PREFERRED_SIZE,
																																																																			140,
																																																																			javax.swing.GroupLayout.PREFERRED_SIZE))
																																																				.addGroup(
																																																									layout
																																																														.createSequentialGroup()
																																																														.addComponent(
																																																																			jLabel3)
																																																														.addPreferredGap(
																																																																			javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																																														.addGroup(
																																																																			layout
																																																																								.createParallelGroup(
																																																																													javax.swing.GroupLayout.Alignment.LEADING)
																																																																								.addGroup(
																																																																													layout
																																																																																		.createSequentialGroup()
																																																																																		.addComponent(
																																																																																							bt_add)
																																																																																		.addGap(
																																																																																							18,
																																																																																							18,
																																																																																							18)
																																																																																		.addComponent(
																																																																																							bt_del)
																																																																																		.addGap(
																																																																																							18,
																																																																																							18,
																																																																																							18)
																																																																																		.addComponent(
																																																																																							bt_save))
																																																																								.addComponent(
																																																																													jScrollPane2,
																																																																													javax.swing.GroupLayout.PREFERRED_SIZE,
																																																																													472,
																																																																													javax.swing.GroupLayout.PREFERRED_SIZE)))))
																																.addGroup(
																																					layout
																																										.createSequentialGroup()
																																										.addGap(
																																															31,
																																															31,
																																															31)
																																										.addComponent(
																																															jScrollPane1,
																																															javax.swing.GroupLayout.PREFERRED_SIZE,
																																															751,
																																															javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addContainerGap(
																											29,
																											Short.MAX_VALUE)));
		layout
							.setVerticalGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
																	layout
																						.createSequentialGroup()
																						.addContainerGap()
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(
																																					jcb_MerType,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addComponent(
																																					jLabel1)
																																.addComponent(
																																					jLabel2)
																																.addComponent(
																																					jsp_MerCount,
																																					javax.swing.GroupLayout.PREFERRED_SIZE,
																																					javax.swing.GroupLayout.DEFAULT_SIZE,
																																					javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.LEADING)
																																.addGroup(
																																					layout
																																										.createSequentialGroup()
																																										.addGap(
																																															27,
																																															27,
																																															27)
																																										.addComponent(
																																															jLabel3))
																																.addGroup(
																																					layout
																																										.createSequentialGroup()
																																										.addGap(
																																															14,
																																															14,
																																															14)
																																										.addComponent(
																																															jScrollPane2,
																																															javax.swing.GroupLayout.PREFERRED_SIZE,
																																															92,
																																															javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addPreferredGap(
																											javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addGroup(
																											layout
																																.createParallelGroup(
																																					javax.swing.GroupLayout.Alignment.BASELINE)
																																.addComponent(
																																					bt_add)
																																.addComponent(
																																					bt_del)
																																.addComponent(
																																					bt_save))
																						.addPreferredGap(
																											javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																											9,
																											Short.MAX_VALUE)
																						.addComponent(
																											jScrollPane1,
																											javax.swing.GroupLayout.PREFERRED_SIZE,
																											256,
																											javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addContainerGap()));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {
		if (merchandiseRetailId == null) {
			merchandiseRetailId = UUID.randomUUID().toString().replace("-", "");
		}
		String[] arg = { ((ItemData) jcb_MerType.getSelectedItem()).code, jsp_MerCount.getValue().toString(), userName,
							merchandiseRetailId };
		DbLogicServie.insertMerRetailInfo(arg);
		setTable();
	}

	@SuppressWarnings("unchecked")
	void setTable() {
		String[] arg = { null, merchandiseRetailId };
		List list = merDetailList = DbLogicServie.getMerRetailDetails(arg);
		MerchandiseRetailTabelModel mrt = new MerchandiseRetailTabelModel(list);
		mrt.setData(list);
		tb_Merchandise.setModel(mrt);
		TableColumnModel columnModel = tb_Merchandise.getColumnModel();
		TableColumn column = columnModel.getColumn(0);
		column.setMinWidth(0);
		column.setMaxWidth(0);

	}

	private void bt_delActionPerformed(java.awt.event.ActionEvent evt) {
		int[] row = tb_Merchandise.getSelectedRows();
		for (int i = 0; i < row.length; i++) {
			merchandiseRetailIds.add(tb_Merchandise.getValueAt(row[i], 0).toString());
		}
		if (DbLogicServie.delMerRetailInfo(merchandiseRetailIds)) {
			setTable();
			JOptionPane.showMessageDialog(null, "剔除成功!", "提示信息", JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {
		BigDecimal totalPrice = new BigDecimal("0");
		for (MerRetail mr : merDetailList) {
			totalPrice = totalPrice.add(mr.getMerRetailTotalPrice());
		}
		Object[] arg = { merchandiseRetailId, totalPrice.toString(),
							Timestamp.valueOf(DateUtil.getNowDateByFormat(DateUtil.YMDHMS)), userName,
							jTextArea1.getText() };
		if (DbLogicServie.insertMerRetailTotal(arg)) {
			merchandiseRetailId = null;
			JOptionPane.showMessageDialog(null, "共【" + merDetailList.size() + "】笔记录,【" + totalPrice + "】元，保存成功!",
								"提示信息", JOptionPane.INFORMATION_MESSAGE);
			setTable();
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MerchandiseRetail("").setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton bt_add;
	private javax.swing.JButton bt_del;
	private javax.swing.JButton bt_save;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JComboBox jcb_MerType;
	private javax.swing.JSpinner jsp_MerCount;
	private javax.swing.JTable tb_Merchandise;
	// End of variables declaration//GEN-END:variables

}